import os
from dotenv import load_dotenv

load_dotenv()

# === FIXED COIN LIST ===
COINS = ["BTC", "ETH", "SOL", "XRP", "BNB", "ADA", "AVAX", "DOT", "ATOM", "DOGE"]

# === API KEYS & TOKENS ===
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")
OKX_API_KEY = os.getenv("OKX_API_KEY", "")
OKX_SECRET = os.getenv("OKX_SECRET", "")
OKX_PASSWORD = os.getenv("OKX_PASSWORD", "")

# === TRADING PARAMETERS ===
TRADE_SIZE_USD = 1000
MAX_OPEN_TRADES = 3
STOP_LOSS_PCT = 0.015
TP1_PCT = 0.020
TP2_PCT = 0.030
TP3_PCT = 0.045
TP1_SELL_PCT = 0.40
TP2_SELL_PCT = 0.40
TP3_SELL_PCT = 0.20
MIN_SIGNAL_SCORE = 75
SCAN_INTERVAL_MINUTES = 15
EMERGENCY_DROP_PCT = 0.10
ALERT_COOLDOWN_HOURS = 6
COINGECKO_DELAY_SECONDS = 10
DAILY_LOSS_LIMIT_USD = 200
WEEKLY_LOSS_LIMIT_USD = 400
COOLDOWN_AFTER_LOSS = {1: 1, 2: 4, 3: 24}  # loss number: hours

# === STRATEGY CONSTANTS ===
TIMEFRAME_4H = "4H"
TIMEFRAME_1H = "1H"
TIMEFRAME_1M = "1m"
CANDLES_COUNT = 50
EMA21_PERIOD = 21
EMA50_PERIOD = 50
RSI_PERIOD = 14
VOLUME_AVG_PERIOD = 20
SR_PERIOD = 20
EMA_THRESHOLD = 0.005
SIDEWAYS_ENTRY_THRESHOLD = 0.015

# === FILES ===
DB_FILE = "trades.db"
LOG_FILE = "bot.log"

# === OKX ===
OKX_BASE_URL = "https://www.okx.com"

# === SERVICE ===
SERVICE_FILE = "almaany.service"
exit